version: "3.7"

services:
  database-restore:
    image: keltuo/mysql-restore-s3
    container_name: ${PROJECT_NAME}_database_restore
    restart: always
    environment:
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET_BACKUPS}
      - S3_PREFIX=${S3_PREFIX}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - SCHEDULE=${RESTORE_SCHEDULE}
